### ISSUE TITLE
Move Mount / Umount into pkg for consumption by Singularity

### ISSUE THREAD

**Issue by dtrudg** [sylabs/sif#206]
Move experimental Mount / Umount into `pkg` for consumption by Singularity.

Can keep them behind the experimental env var gate in siftool.

**Comment by tri-adam** [comment]
Probably obvious, but prior to this move, we need to ensure we're _comfortable enough_ with adding this to the `v2` API (and the compatibility guarantees that implies.) Off the top of my head, this means:

- The name of the `func`s are reasonable and self-explanatory. 
- The fixed `func` params must be supplied for any foreseeable functionality, and wouldn't be better served as functional options.
- The return type(s) are correct.

The biggest question I have is whether `Unmount` should be a method called on a value returned by `Mount`, or whether the two should be distinct. Any thoughts there @dtrudg ?

**Comment by dtrudg** [comment]
> The biggest question I have is whether `Unmount` should be a method called on a value returned by `Mount`, or whether the two should be distinct. Any thoughts there @dtrudg ?

For consumption with Singularity (and thinking about run / conmon later) it is easiest if `Unmount` is distinct from `Mount`. Preparation of a container happens always in a separate process than cleanup, so we can't pass a struct that implements a method, nor do we have a convenient way to track state to e.g. assign a UUID per mount.

If `Mount` was/could return a value then it would likely be sensible to return a PID of the FUSE process, and implement unmount by killing the process rather than `fusermount -u`.

Perhaps we can discuss this a bit ASAP?

**Comment by tri-adam** [comment]
> > The biggest question I have is whether `Unmount` should be a method called on a value returned by `Mount`, or whether the two should be distinct. Any thoughts there @dtrudg ?
> 
> For consumption with Singularity (and thinking about run / conmon later) it is easiest if `Unmount` is distinct from `Mount`. Preparation of a container happens always in a separate process than cleanup, so we can't pass a struct that implements a method, nor do we have a convenient way to track state to e.g. assign a UUID per mount.

Makes sense. Same argument applies for `siftool`.

> If `Mount` was/could return a value then it would likely be sensible to return a PID of the FUSE process, and implement unmount by killing the process rather than `fusermount -u`.

Yeah. I don't see an obvious way to do this, unfortunately.

> Perhaps we can discuss this a bit ASAP?

Sure thing!

**Comment by tri-adam** [comment]
Just to summarize our discussion here @dtrudg, it looks like we're quite comfortable with the stability of the API, and only small improvement is the nomenclature. The mount/unmount `func`s are now decidedly FUSE-specific, so proposing the following renames prior to making the APIs public:

- `Mount` -> `MountFUSE`
- `Unmount` -> `UnmountFUSE`
