### ISSUE TITLE
New Package for Usermode Functionality?

### ISSUE THREAD

**Issue by tri-adam** [sylabs/sif#210]
I think we should consider moving the usermode functionality from #191 and #205 (and eventually #192) to a separate package within this module. `github.com/sylabs/sif/v2/pkg/sif` is focussed on creating and modifying SIF images, whereas this functionality is about using them at a higher level.

`MountFUSE` and `UnmountFUSE` are currently exposed in `github.com/sylabs/sif/v2/pkg/sif`, but have not yet made it into a tagged release, so we are still free to make this change. That being said, https://github.com/sylabs/singularity/pull/711 requires this work, so we should make this switch and cut a release soon if we're going to do so.

Some suggestions:

- `github.com/sylabs/sif/v2/pkg/user`
- `github.com/sylabs/sif/v2/pkg/usermode`
- `github.com/sylabs/sif/v2/pkg/unpriv`

**Comment by dtrudg** [comment]
My vote would be for `user`
