### ISSUE TITLE
Update CI to ensure vendor folder is in sync with go.mod & go.sum

### ISSUE THREAD

**Issue by bauerm97** [sylabs/sif#28]
As a follow-up to #24, we should add a check to our CI to make sure that `vendor/` stays in sync with `go.mod` and `go.sum` files.

**Comment by tri-adam** [comment]
Go has `-mod=readonly` which can be used for this purpose. Unfortunately, it is incompatible with `-mod=vendor` ([ref](https://github.com/golang/go/issues/30404#issuecomment-468052126)).

Ideally, we should bail out as early as possible when `go.mod` does not match the source code. After some experimentation, it looks like running `go list -mod=readonly ./... >/dev/null` before any commands that modify `go.mod` is a viable option.
