### ISSUE TITLE
Remove build job from circleci

### ISSUE THREAD

**Issue by jscook2345** [sylabs/sif#31]
I think that the `build` job is redundant if a workflow is being used to build and test `sif` (which it appears to be) and thus should be removed.

**Comment by tri-adam** [comment]
The `build` job is called by default when you do a `circleci build`. It's useful for local testing prior to submitting a PR.

**Comment by jscook2345** [comment]
Ah yes OK. I wonder if we can combine the workflow jobs to remove the repetition?

**Comment by tri-adam** [comment]
Will migrate to config version 2.1 as part of #34. In light of that, think we can proceed with this as originally described (since the local CLI doesn't support config versions >= 2.1).
