### ISSUE TITLE
Deprecate `pkg/user` package?

### ISSUE THREAD

**Issue by tri-adam** [sylabs/sif#323]
The `user` package was originally added to support the SingularityCE Roadmap, as well as support reuse in packages such as [Anchore Stereoscope](https://github.com/anchore/stereoscope). With SingularityCE having its own (arguably more advanced) FUSE code, and having gone a different direction with Stereoscope (https://github.com/anchore/stereoscope/pull/125), it may make sense to deprecate this package (and remove it in the next major version.)

As additional data: `pkg.go.dev` is not currently showing any known importers aside from `github.com/sylabs/singularity/v4` (ref: https://pkg.go.dev/github.com/sylabs/sif/v2/pkg/user?tab=importedby).

**Comment by preminger** [comment]
If & when https://github.com/sylabs/singularity/pull/2199 is merged, the aforementioned importers from `github.com/sylabs/singularity/v4` will have been removed.
