### ISSUE TITLE
Fails to build with latest protonmail/go-crypto

### ISSUE THREAD

**Issue by mdosch** [sylabs/sif#388]
Dear maintainer,

it seems your package doesn't build against github.com/protonmail/go-crypto v1.1.0 which was released today:

```
# github.com/sylabs/sif/pkg/integrity
src/github.com/sylabs/sif/pkg/integrity/clearsign.go:42:57: not enough arguments in call to clearsign.Encode
	have (io.Writer, *packet.PrivateKey, *packet.Config)
	want (io.Writer, *packet.PrivateKey, *packet.Config, map[string]string)
```

**Comment by tri-adam** [comment]
Thanks @mdosch, tracking the fix you added upstream, looks like that should resolve the issue.

**Comment by mdosch** [comment]
Yes, it was an issue in go-crypto.
