### ISSUE TITLE
sif push gives a bunch of warnings

### ISSUE THREAD

**Issue by sushma-4** [sylabs/sif#40]
#### Version
3.3.0-rc1

#### What's happening
```
$ singularity push frtest.sif oras://localhost:5000/fakeroot
INFO:    No tag or digest found, using default: latest
WARN[0000] encountered unknown type appliciation/vnd.sylabs.sif.layer.tar; children may not be fetched 
WARN[0000] encountered unknown type application/vnd.sylabs.sif.config.v1+json; children may not be fetched 
WARN[0000] reference for unknown type: appliciation/vnd.sylabs.sif.layer.tar  digest="sha256:5e15d96e9a185c66e4e7c0f3ba4b96c383cba8e8769ed2c704906abecd6ef812" mediatype=appliciation/vnd.sylabs.sif.layer.tar size=25890816
WARN[0000] reference for unknown type: application/vnd.sylabs.sif.config.v1+json  digest="sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" mediatype=application/vnd.sylabs.sif.config.v1+json size=0
```
**Although these warnings are not preventing the ``push`` from happening, but Singularity should output saying that the image was successfully pushed**

Discussed this on slack but noting it here so we don't lose track

**Comment by jscook2345** [comment]
@sushma-4 

I think this is fixed by the following: https://github.com/sylabs/singularity/pull/3791

@ikaneshiro 

Can you confirm?

**Comment by sushma-4** [comment]
Yes, I think this is the same issue.. didn't know about the other one Ian opened..

**Comment by ikaneshiro** [comment]
@jscook2345 Correct, and thats one of the prs I asked to be cherrypicked for the next rc.
