### ISSUE TITLE
Name variable in sif info not clear

### ISSUE THREAD

**Issue by sushma-4** [sylabs/sif#41]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

``
singularity sif info 1 jupyter.sif (where 1 is the Descriptor ID for Def file)
``
displays no name of the def file used to build the container. IDK if that's what its supposed to output but a ``.`` does not make much sense 

Also, Singularity gives no error when Descriptor IDs not in range are used with the container file, Like for a SIF with 3 partitions and you say ``singularity sif info 4``

### Actual behavior
```
Descr slot#: 0
  Datatype:  Def.FILE
  ID:        1
  Used:      true
  Groupid:   1
  Link:      NONE
  Fileoff:   32768
  Filelen:   1128
  Ctime:     2018-12-20 16:05:16 +0530 IST
  Mtime:     2018-12-20 16:05:16 +0530 IST
  UID:       0
  Gid:       0
  Name:      .
```

**Comment by sashayakovtseva** [comment]
The name issue happens on Singularity side during SIF assembling: a name for def file partition is not set, so in `pkg/sif/create.go:99` it is set to `.`.

The out of range descriptor does print an error: 
```
$ singularity sif dump 4 env-new.sif 
Error for command "dump": descriptor not in range or currently unused

Usage:
  singularity [global options...] sif dump <descriptorid> <containerfile>

Run 'singularity sif dump --help' for more detailed usage information.
```

However, I agree that the usage part can be omitted here.

**Comment by sashayakovtseva** [comment]
I think this one can be closed in this repo, @sushma-4 feel free to open this issue on singularity side if you think it should be fixed.
