### ISSUE TITLE
Get header info by providing only first x Peek'd bytes

### ISSUE THREAD

**Issue by dctrud** [sylabs/sif#5]
If a SIF file is being streamed somewhere it would be handy to be able to pull at the header information by passing some function the first x bytes - where x >= than the header length.

E.g. you could then look at the header and verify things like UUID, architecture are as expected before continuing to deal with the file:

Usage something along the lines of....

```
br := bufio.NewReader(mySIFStream)
headerBytes, err := br.Peek(sif.HEADER_SIZE)
header, err := sif.headerFromBytes(headerBytes)
if notWhatIWant(header) {
  return fmt.Error("Here be dragons")
}
handleOKSIF(br)
```

**Comment by yhcote** [comment]
An implementation has been submitted to add this feature.
