### ISSUE TITLE
GetFromDescr return []*Descriptor

### ISSUE THREAD

**Issue by bauerm97** [sylabs/sif#8]
I think it would be a pretty easy change to make in `sif/lookup.go`. Would be beneficial to return *all* descriptors matching the fields of the function argument in `func (fimg *FileImage) GetFromDescr(descr Descriptor) (*Descriptor, int, error)`.

New function could be:

`func (fimg *FileImage) GetFromDescr(descr Descriptor) ([]*Descriptor, int, error)`

**Comment by yhcote** [comment]
This will be part of another family ending with *All instead. We need to obviously be able to lookup descriptors that come from a lookup with multiple results but I wanna separate that from the first ones doing lookups for unique objects.

**Comment by yhcote** [comment]
Changes from commit 8ad2fb6 implement that feature and also this has been extended to other lookup routines that may return multiple descriptors.
